format = """
[░▒▓](#3B4252)\
$username\
[   ](bg:#3B4252 fg:#ffffff)\
[](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#86BBD8)\
$git_branch\
$git_status\
[](fg:#86BBD8 bg:#06969A)\
[](fg:#06969A bg:#33658A)\
$cmd_duration\
[ ](fg:#33658A)\
"""

[username]
show_always = true
style_user = "bg:#3B4252 fg:#ffffff"
style_root = "bg:#3B4252 fg:#ffffff"
format = '[  $user]($style)'

[directory]
style = "fg:#ffffff bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#04c4ca"
format = '[[ $symbol $branch ](fg:#394260 bg:#86BBD8)]($style)'

[git_status]
style = "bg:#04c4ca"
format = '[[($all_status$ahead_behind )](fg:#394260 bg:#86BBD8)]($style)'
